name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'

      # إنشاء android تلقائي
      - run: flutter create .

      # إضافة أذونات البلوتوث تلقائي
      - run: |
          sed -i '/<manifest/a\
          <uses-permission android:name="android.permission.BLUETOOTH"/>\
          <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>\
          <uses-permission android:name="android.permission.BLUETOOTH_CONNECT"/>\
          <uses-permission android:name="android.permission.BLUETOOTH_SCAN"/>\
          <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>' android/app/src/main/AndroidManifest.xml

      # تحميل المكتبات
      - run: flutter pub get

      # بناء التطبيق
      - run: flutter build apk --release

      # رفع APK
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/
